Correctly handle `pymysql.err.InternalError` in `mysql` module.
